# Generated by Django 4.2.7 on 2023-12-17 19:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Worker_ID', models.IntegerField(validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)])),
                ('Full_Name', models.CharField(max_length=20)),
                ('Work_Days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='shift date')),
                ('Shift', models.CharField(choices=[('mo', 'Morning'), ('af', 'Afternoon'), ('ni', 'Night')], max_length=10)),
                ('Worker', models.ForeignKey(choices=[('5', 'Sun Laria'), ('7', 'Meri Laria')], on_delete=django.db.models.deletion.CASCADE, to='shift_manager.worker')),
            ],
        ),
    ]
