# Generated by Django 4.2.7 on 2023-12-17 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='Worker',
            field=models.ForeignKey(choices=[('23223232', 'Sun Laria'), ('10003', 'Meri Laria')], on_delete=django.db.models.deletion.CASCADE, to='shift_manager.worker'),
        ),
    ]
