# Generated by Django 5.0 on 2023-12-30 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift_manager', '0003_alter_shift_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='Worker_ID',
        ),
    ]
